
QuestHelper_Pref = {
}
QuestHelper_UID = "aign329W7XXKIlLvRrRvK8DkDbn6yPr0"
QuestHelper_SaveDate = 1527103479
QuestHelper_Errors = {
	["version"] = 1,
	["crash"] = {
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:384: in function <...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:383>\n[C]: in function `Show'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:411: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `SaveBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:175: in function `ReassignBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:83: in function <Interface\\AddOns\\Bartender4\\ActionBars.lua:65>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:539: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:629: in function <...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:615>\n[C]: in function `LoadAddOn'\nInterface\\FrameXML\\UIParent.lua:235: in function `UIParentLoadAddOn'\nInterface\\FrameXML\\UIParent.lua:258: in function `CombatLog_LoadUI'\nInterface\\FrameXML\\UIParent.lua:482: in function <Interface\\FrameXML\\UIParent.lua:454>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [1]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:384: in function <...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:383>\n[C]: in function `Show'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:411: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `SaveBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:175: in function `ReassignBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:83: in function <Interface\\AddOns\\Bartender4\\ActionBars.lua:65>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:539: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:629: in function <...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:615>\n[C]: in function `LoadAddOn'\nInterface\\FrameXML\\UIParent.lua:235: in function `UIParentLoadAddOn'\nInterface\\FrameXML\\UIParent.lua:258: in function `CombatLog_LoadUI'\nInterface\\FrameXML\\UIParent.lua:482: in function <Interface\\FrameXML\\UIParent.lua:454>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [2]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:384: in function <...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:383>\n[C]: in function `Show'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:411: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `SaveBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:175: in function `ReassignBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:83: in function <Interface\\AddOns\\Bartender4\\ActionBars.lua:65>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:539: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:629: in function <...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:615>\n[C]: in function `LoadAddOn'\nInterface\\FrameXML\\UIParent.lua:235: in function `UIParentLoadAddOn'\nInterface\\FrameXML\\UIParent.lua:258: in function `CombatLog_LoadUI'\nInterface\\FrameXML\\UIParent.lua:482: in function <Interface\\FrameXML\\UIParent.lua:454>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [3]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:384: in function <...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:383>\n[C]: in function `Show'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:411: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `SaveBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:175: in function `ReassignBindings'\nInterface\\AddOns\\Bartender4\\ActionBars.lua:83: in function <Interface\\AddOns\\Bartender4\\ActionBars.lua:65>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:539: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551: in function `EnableAddon'\n...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:629: in function <...s\\AckisRecipeList\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:615>\n[C]: in function `LoadAddOn'\nInterface\\FrameXML\\UIParent.lua:235: in function `UIParentLoadAddOn'\nInterface\\FrameXML\\UIParent.lua:258: in function `CombatLog_LoadUI'\nInterface\\FrameXML\\UIParent.lua:482: in function <Interface\\FrameXML\\UIParent.lua:454>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [4]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [5]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [6]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [7]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:50",
		}, -- [8]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:83: in function `GupPet_AutoCompanionResumonSetEnable'\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:29: in function `GupPet_AutoCompanionBoot'\nInterface\\AddOns\\GupPet\\GupPet.lua:117: in function `GupPet_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:51",
		}, -- [9]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:83: in function `GupPet_AutoCompanionResumonSetEnable'\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:29: in function `GupPet_AutoCompanionBoot'\nInterface\\AddOns\\GupPet\\GupPet.lua:117: in function `GupPet_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:51",
		}, -- [10]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:83: in function `GupPet_AutoCompanionResumonSetEnable'\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:29: in function `GupPet_AutoCompanionBoot'\nInterface\\AddOns\\GupPet\\GupPet.lua:117: in function `GupPet_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:51",
		}, -- [11]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:83: in function `GupPet_AutoCompanionResumonSetEnable'\nInterface\\AddOns\\GupPet\\GupPet_AutoCompanion.lua:29: in function `GupPet_AutoCompanionBoot'\nInterface\\AddOns\\GupPet\\GupPet.lua:117: in function `GupPet_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:51",
		}, -- [12]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:52",
		}, -- [13]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:52",
		}, -- [14]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:52",
		}, -- [15]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "esES",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  DrDamage, v1.7.8_release\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  GearScore, v3.1.17 - Release\n  Grid, v1.30300.1308\n  GridIndicatorIconBar, vv1.3-beta\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PowerAuras, v3.0.0J\n  QuestHelper, v1.4.0\n  Recount, v1111\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TellMeWhen, v1.2.4\n  TidyPlates, v5.11.5\n  TidyPlatesGrey\n  TidyPlatesNeon, v3\n  TomTom, vSVN\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  Koordinator, v3.32\n  DBMCore\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:18: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:238: in function `TellMeWhen_Group_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:205: in function `TellMeWhen_Update'\nInterface\\AddOns\\TellMeWhen\\TellMeWhen.lua:108: in function <Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:94>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2018-05-23 16:24:52",
		}, -- [16]
	},
}
QuestHelper_Collector = {
	["1.4.0 on 3.3.5/esES/1"] = {
		["monster"] = {
		},
		["warp"] = {
		},
		["flight_times"] = {
		},
		["modified"] = 1527103495,
		["flight_master"] = {
		},
		["achievement"] = {
		},
		["fishing"] = {
		},
		["item"] = {
		},
		["realms"] = {
			["WoWArg"] = 1,
		},
		["worldloot"] = {
		},
		["object"] = {
		},
		["quest"] = {
			[8115] = {
				["groupcount"] = 0,
				["criteria_1_text"] = "Captura 5 bases",
				["special_item"] = false,
				["daily"] = false,
				["name"] = "Controla cinco bases",
				["items_reward"] = {
					[20132] = 1,
				},
				["criteria_1_type"] = "event",
				["level"] = 60,
				["tag"] = "JcJ",
			},
			[13186] = {
				["groupcount"] = 0,
				["criteria_1_text"] = "Aparatos de asedio de la Horda destruidos: 0/3",
				["special_item"] = false,
				["daily"] = false,
				["name"] = "Parar el asedio",
				["items_reward"] = {
					[43228] = 10,
				},
				["criteria_1_type"] = "monster",
				["level"] = 80,
				["tag"] = "JcJ",
			},
			[12963] = {
				["groupcount"] = 0,
				["daily"] = true,
				["name"] = "Envío: bibelot de sol cambiante",
				["criteria_1_text"] = "Bibelot de sol cambiante: 0/1",
				["special_item"] = false,
				["criteria_1_type"] = "item",
				["items_reward"] = {
					[41596] = 1,
				},
				["level"] = -1,
			},
			[236] = {
				["groupcount"] = 0,
				["criteria_1_text"] = "Ascuas eternas: 3/10",
				["special_item"] = false,
				["daily"] = false,
				["name"] = "Combustible para los demoledores",
				["items_reward"] = {
					[43228] = 10,
				},
				["criteria_1_type"] = "item",
				["level"] = 80,
				["tag"] = "JcJ",
			},
			[11731] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Lanzamiento de antorchas",
				["criteria_1_text"] = "Acierta en 8 blandones",
				["special_item"] = false,
				["criteria_1_type"] = "event",
				["items_reward"] = {
					[23247] = 5,
				},
				["level"] = -1,
			},
			[5382] = {
				["groupcount"] = 0,
				["criteria_2_text"] = "Has quemado los restos de Eva Sarkhoff: 0/1",
				["criteria_1_text"] = "Doctor Theolen Krastinov matado: 0/1",
				["special_item"] = false,
				["criteria_3_text"] = "Has quemado los restos de Lucien Sarkhoff: 0/1",
				["daily"] = false,
				["name"] = "Doctor Theolen Krastinov, el Carnicero",
				["tag"] = "Mazmorra",
				["criteria_3_type"] = "object",
				["level"] = 60,
				["criteria_1_type"] = "monster",
				["criteria_2_type"] = "object",
			},
			[13181] = {
				["groupcount"] = 0,
				["criteria_1_text"] = "Victoria en el Lago Conquista del Invierno",
				["special_item"] = false,
				["daily"] = false,
				["name"] = "Victoria en Conquista del Invierno",
				["items_reward"] = {
					[43228] = 10,
				},
				["criteria_1_type"] = "event",
				["level"] = 80,
				["tag"] = "JcJ",
			},
			[70] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "La leyenda de Stalvan",
				["criteria_1_text"] = "Una carta sin entregar: 1/1",
				["special_item"] = false,
				["level"] = 28,
				["criteria_1_type"] = "item",
			},
			[48] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Dulce ámbar",
				["criteria_1_text"] = "Agua de manantial sagrado: 0/1",
				["special_item"] = false,
				["level"] = 44,
				["criteria_1_type"] = "item",
			},
			[1097] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "La tarea de Elmore",
				["level"] = 15,
				["special_item"] = false,
			},
			[13159] = {
				["groupcount"] = 0,
				["items_choice"] = {
					[44344] = 1,
					[44343] = 1,
					[44342] = 1,
					[44345] = 1,
				},
				["criteria_1_text"] = "Cianigosa asesinada: 0/1",
				["special_item"] = 42482,
				["daily"] = false,
				["name"] = "Contención",
				["level"] = 77,
				["criteria_1_type"] = "monster",
				["tag"] = "Mazmorra",
			},
			[117] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Cerveza Cebatruenos",
				["criteria_1_text"] = "Lúpulos: 3/5",
				["special_item"] = false,
				["criteria_1_type"] = "item",
				["items_reward"] = {
					[1262] = 1,
				},
				["level"] = 15,
			},
			[13538] = {
				["groupcount"] = 0,
				["criteria_1_text"] = "Destruye una de las tres torres sur: 0/1",
				["special_item"] = false,
				["daily"] = false,
				["name"] = "Sabotaje al sur",
				["items_reward"] = {
					[43228] = 10,
				},
				["criteria_1_type"] = "monster",
				["level"] = 80,
				["tag"] = "JcJ",
			},
			[26012] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Problemas en Reposo del Dragón",
				["criteria_1_text"] = "Habla con Krasus en el Templo del Reposo del Dragón en el Cementerio de Dragones.",
				["special_item"] = false,
				["level"] = 82,
				["criteria_1_type"] = "log",
				["tag"] = "Banda",
			},
			[8114] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Toma el control de cuatro bases",
				["criteria_1_text"] = "Toma el control de las 4 bases",
				["special_item"] = false,
				["level"] = 60,
				["criteria_1_type"] = "event",
				["tag"] = "JcJ",
			},
			[94] = {
				["groupcount"] = 0,
				["daily"] = false,
				["name"] = "Un ojo vigilante",
				["level"] = 21,
				["special_item"] = false,
			},
		},
		["version"] = 8,
	},
}
QuestHelper_Collector_Version = 8
