
QuestHelper_Pref = {
}
QuestHelper_UID = "L2OBvWun1vqJYmY4cmctLV9g9742mcks"
QuestHelper_SaveDate = 1635032248
QuestHelper_Errors = {
	["version"] = 1,
	["crash"] = {
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:98: in function `EasyCopy_OnLoad'\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:138: in function `EasyCopy_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:29",
		}, -- [1]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:98: in function `EasyCopy_OnLoad'\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:138: in function `EasyCopy_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:29",
		}, -- [2]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:98: in function `EasyCopy_OnLoad'\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:138: in function `EasyCopy_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:29",
		}, -- [3]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  Talented, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: in function `(for generator)'\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n[C]: ?\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:98: in function `EasyCopy_OnLoad'\nInterface\\AddOns\\EasyCopy\\EasyCopy.lua:138: in function `EasyCopy_OnEvent'\n[string \"*:OnEvent\"]:1: in function <[string \"*:OnEvent\"]:1>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:29",
		}, -- [4]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "Interface\\AddOns\\QuestHelper\\error.lua:202: C stack overflow",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BrokerBonusScanner, v1.2\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  SpellFlashArgentTournamentMounts, v1.12\n  SpellFlashRacials, v1.10\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "(tail call): ?\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\Altoholic\\Frames\\TabOptions.lua:436: in function `Set'\nInterface\\AddOns\\Altoholic\\Altoholic.lua:269: in function <Interface\\AddOns\\Altoholic\\Altoholic.lua:255>\n[string \"safecall Dispatcher[1]\"]:4: in function <[string \"safecall Dispatcher[1]\"]:4>\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:13: in function `?'\n...Tom\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:91: in function `Fire'\n...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:120: in function <...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:119>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:35",
		}, -- [5]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BrokerBonusScanner, v1.2\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  SpellFlashArgentTournamentMounts, v1.12\n  SpellFlashRacials, v1.10\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\Altoholic\\Frames\\TabOptions.lua:436: in function `Set'\nInterface\\AddOns\\Altoholic\\Altoholic.lua:269: in function <Interface\\AddOns\\Altoholic\\Altoholic.lua:255>\n[string \"safecall Dispatcher[1]\"]:4: in function <[string \"safecall Dispatcher[1]\"]:4>\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:13: in function `?'\n...Tom\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:91: in function `Fire'\n...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:120: in function <...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:119>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:35",
		}, -- [6]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BrokerBonusScanner, v1.2\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  SpellFlashArgentTournamentMounts, v1.12\n  SpellFlashRacials, v1.10\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n...\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\Altoholic\\Frames\\TabOptions.lua:436: in function `Set'\nInterface\\AddOns\\Altoholic\\Altoholic.lua:269: in function <Interface\\AddOns\\Altoholic\\Altoholic.lua:255>\n[string \"safecall Dispatcher[1]\"]:4: in function <[string \"safecall Dispatcher[1]\"]:4>\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:13: in function `?'\n...Tom\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:91: in function `Fire'\n...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:120: in function <...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:119>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:35",
		}, -- [7]
		{
			["game_version"] = "3.3.5",
			["toc_version"] = "1.4.0",
			["message"] = "...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: bad argument #6 to 'format' (string expected, got nil)",
			["silent"] = true,
			["locale"] = "enUS",
			["addons"] = "  NPCScan, v3.3.5.5\n  NPCScanOverlay, v3.3.5.1\n  AckisRecipeList, vDevel\n  ActionBarSaver\n  ACP, v3.3.4 \n  Altoholic, vv3.3.002\n  Atlas, v1.16.1\n  AtlasBattlegrounds, v1.16.1\n  AtlasDungeonLocs, v1.16.1\n  AtlasOutdoorRaids, v1.16.1\n  AtlasTransportation, v1.16.1\n  AtlasLoot, v|cffFF8400AtlasLoot Enhanced v5.11.02|r\n  AtlasLootFu, v5.11.02\n  BagBrother\n  Bagnon, v4.1.1\n  BagnonForever, v1.1.2\n  BagnonTooltips\n  BagnonAccountSearch, v1.7.0\n  Bartender4, v4.4.2\n  BonusScanner, v5.3\n  BrokerBonusScanner, v1.2\n  BunnyHunter, v1.6\n  ClassLoot, vv1.7.2\n  CollectMe, v1.1.14\n  CookingHelper, v2.03\n  Currency, v3.0\n  DataStore\n  DataStoreAchievements, v3.3.001\n  DataStoreAuctions, v3.3.001\n  DataStoreCharacters, v3.3.001\n  DataStoreContainers, v3.3.001\n  DataStoreCrafts, v3.3.001\n  DataStoreCurrencies, v3.3.001\n  DataStoreInventory, v3.3.001\n  DataStoreMails, v3.3.001\n  DataStorePets, v3.3.001\n  DataStoreQuests, v3.3.001\n  DataStoreReputations, v3.3.001\n  DataStoreSkills, v3.3.001\n  DataStoreSpells, v3.3.001\n  DataStoreStats, v3.3.001\n  DataStoreTalents, v3.3.001\n  EasyCopy, v2.5\n  EveryQuest, v2.3r162\n  EveryQuestQuestGivers, v29\n  Factionizer, v30300.4\n  FarmIt\n  FishingBuddy, v0.9.8p1\n  Gatherer, v3.1.14\n  GearScore, v3.1.17 - Release\n  GMGenie, v0.7.3\n  GupPet, v1.241\n  GupPetCollectMe\n  HandyNotes, v1.1.5\n  HandyNotesQuestGivers, v0.2.0\n  HunterHelper, v1.64\n  ItemRack, v2.243\n  KHunterTimers, v3.2.5\n  Ace2\n  LightHeaded, v304\n  loremaster, vv2.033 20100226\n  Nauticus, v3.2.0\n  OmniCC, v3.0.2\n  Overachiever, v0.54\n  PlateBuffs, v1.5.4beta (r176)\n  Postal, v3.3.2\n  PowerAuras, v3.0.0J\n  Quartz, v3.0.3.1\n  QuestCompletist, v0.1\n  QuestHelper, v1.4.0\n  RaidRoll\n  RaidRollEPGP\n  RaidRollLootTracker\n  RangeDisplay, vRangeDisplay-r290\n  RecipeRadar, v1.33\n  Recount, v1111\n  ShadowedUnitFrames, vv3.2.12\n  SpellFlash, v4.0.1\n  SpellFlashArgentTournamentMounts, v1.12\n  SpellFlashRacials, v1.10\n  Talented, vv2.4.6c-release\n  TalentedSpecTabs, vv2.4.6c-release\n  TidyPlates, v5.13.3 (R39)\n  TidyPlatesGrey\n  TidyPlatesNeon\n  TipTac, v10.05.01\n  TipTacItemRef, v10.02.27\n  TipTacTalents, v10.02.27\n  TomTom, vSVN\n  TrackoMatique, v3.4.7\n  ViperNotify, v1.3.9\n  XPerl, v3.0.8\n  XPerlArcaneBar\n  XPerlOptions\n  XPerlPartyPet\n  XPerlParty\n  XPerlPlayerBuffs\n  XPerlPlayerPet\n  XPerlPlayer\n  XPerlRaidAdmin\n  XPerlRaidHelper\n  XPerlRaidPets\n  XPerlRaidFrames\n  XPerlTargetTarget\n  XPerlTarget\n  ZHunterMod\n  Koordinator, v3.32\n  DBMCore\n  DBMSpellTimers\n  DBMBurningCrusade\n",
			["stack"] = "(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\QuestHelper\\error.lua:202: in function <Interface\\AddOns\\QuestHelper\\error.lua:197>\n...\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\n[C]: in function `format'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:432: in function `ScriptErrorsFrame_Update'\n...e\\AddOns\\Blizzard_DebugTools\\Blizzard_DebugTools.lua:413: in function `ScriptErrorsFrame_OnError'\n[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:22: in function <[string \"Interface\\FrameXML\\BasicControls.xml:<Scrip...\"]:4>\n(tail call): ?\n(tail call): ?\nInterface\\AddOns\\Altoholic\\Frames\\TabOptions.lua:436: in function `Set'\nInterface\\AddOns\\Altoholic\\Altoholic.lua:269: in function <Interface\\AddOns\\Altoholic\\Altoholic.lua:255>\n[string \"safecall Dispatcher[1]\"]:4: in function <[string \"safecall Dispatcher[1]\"]:4>\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:13: in function `?'\n...Tom\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:91: in function `Fire'\n...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:120: in function <...ace\\AddOns\\TomTom\\libs\\AceEvent-3.0\\AceEvent-3.0.lua:119>\n",
			["local_version"] = "1.4.0",
			["timestamp"] = "2021-10-23 20:37:35",
		}, -- [8]
	},
}
QuestHelper_Collector = {
	["1.4.0 on 3.3.5/enUS/2"] = {
		["monster"] = {
		},
		["warp"] = {
		},
		["flight_times"] = {
		},
		["modified"] = 1635032251,
		["flight_master"] = {
		},
		["achievement"] = {
		},
		["fishing"] = {
		},
		["item"] = {
		},
		["realms"] = {
			["Sin'Dorei"] = 1,
		},
		["worldloot"] = {
		},
		["object"] = {
		},
		["quest"] = {
		},
		["version"] = 8,
	},
}
QuestHelper_Collector_Version = 8
