-- English localization file for enUS and enGB.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("HunterHelper", "enUS", true)
if not L then return end

L["Combat Text"] = true
L["Combat without Pet"] = true
L["Default Dragonhawk Message"] = "You should be using Aspect of the Dragonhawk!"
L["Default Full Mana Message"] = "Mana is full! Turn Viper off!"
L["Default Low Mana Message"] = "Low mana!"
L["Default No Aspect Message"] = "No battle aspect selected!"
L["Default No Pet Message"] = "You do not have a pet!"
L["Default Party Growl Message"] = "Your pet is growling!"
L["Default Pet Aggressive Message"] = "Your pet is Aggressive!"
L["Default Pet Happiness Message"] = "Your pet is not completely happy!"
L["Default Pet Passive Message"] = "Your pet is set to Passive!"
L["Default Solo Growl Message"] = "Your pet is not growling!"
L["Disable Messages"] = true
L["Disable When Solo"] = true
L["Display as Combat Text"] = true
L["Display as Raid Warning"] = true
L["Display Method"] = true
L["Display Method Desc"] = "Determines how warning messages are displayed."
L["Dragonhawk Options"] = true
L["Dragonhawk Warning"] = true
L["Dragonhawk Warning Desc"] = "Warn when you are using Aspect of the Monkey or Hawk and Dragonhawk is available."
L["Enable Sounds"] = true
L["General Settings"] = true
L["Growling in Party"] = "Growling in Party/Raid"
L["Growling while Solo"] = true
L["HH_SLASH_DESC"] = "HunterHelper slash commands (format: /hunterhelper <command> <value>)"
L["High Mana Options"] = "Full Mana Options"
L["High Mana Threshold"] = true
L["High Mana Warning"] = "Full Mana Warning"
L["High Mana Warning Desc"] = "Warn when your mana is full and Aspect of the Viper is on"
L["Low Mana Options"] = true
L["Low Mana Threshold"] = true
L["Low Mana Warning"] = true
L["Low Mana Warning Desc"] = "Warn when your mana is low"
L["Mana/Combat Options"] = true
L["Message"] = true
L["Message Color"] = true
L["No Aspect Options"] = "Battle Aspect Options"
L["No Aspect Warning"] = "Battle Aspect Warning"
L["No Aspect Warning Desc"] = "Select this option to notify you when you go into combat and you do not have a \"Battle Aspect\" -- meaning, if you either do not have any Aspect selected at all, or your current Aspect is \"Aspect of the Cheetah\" or \"Aspect of the Pack\"."
L["None"] = true
L["No Pet Warning"] = true
L["No Pet Warning Desc"] = "Warn when you enter combat without a pet."
L["OFF"] = true
L["ON"] = true
L["Only Notify In Combat"] = true
L["Party Growl Warning"] = true
L["Party Growl Warning Desc"] = "Warn when your pet is using Growl while you are in a party or raid group."
L["Party Size"] = true
L["Party Size Desc"] = "Minimum party or raid size in which to show this warning."
L["Pet Aggressive"] = "Pet on Aggressive"
L["Pet Aggressive Only in Party"] = "Only in Party/Raid"
L["Pet Aggressive Only in Party Desc"] = "Only warn about this when you're in a party.  Some hunters prefer to let their pets roam while playing solo."
L["Pet Aggressive Warning"] = true
L["Pet Aggressive Warning Desc"] = "Warn when your pet is set to Aggressive mode.  While Aggressive, your pet attacks enemies on its own and can cause a lot of trouble in groups."
L["Pet Happiness"] = true
L["Pet Happiness Warning"] = true
L["Pet Happiness Warning Desc"] = "Warn when your pet is unhappy.  Your pet's happiness level directly impacts its performance."
L["Pet Options"] = true
L["Pet Passive"] = "Pet on Passive"
L["Pet Passive Warning"] = true
L["Pet Passive Warning Desc"] = "Warn when your pet is set to Passive mode.  While Passive, your pet does not attack anything unless you tell it to."
L["Raid Warning"] = true
L["Slash Command"] = true
L["Solo Growl Warning"] = true
L["Solo Growl Warning Desc"] = "Warn when your pet is NOT using Growl while you are solo."
L["Sound"] = true
L["Threshold"] = true
L["Toggle Aspect Warning"] = true
L["Toggle Disable When Solo"] = true
L["Toggle Dragonhawk Warning"] = true
L["Toggle High Mana Warning"] = true
L["Toggle Low Mana Warning"] = true
L["Toggle No Pet Warning"] = true
L["Toggle Notify Only in Combat"] = true
L["Toggle Party Growl Warning"] = true
L["Toggle Pet Aggressive Warning"] = true
L["Toggle Pet Happiness Warning"] = true
L["Toggle Pet Passive Warning"] = true
L["Toggle Solo Growl Warning"] = true
L["Toggle Sounds"] = true
L["<Unknown>"] = true
L["Update Interval"] = true
L["Update Interval Desc"] = "Sets how frequently warning messages appear"
